version: '3'

services:
  openwebrx:
    image: jketterl/openwebrx:stable
    devices:
      - "/dev/bus/usb"
    ports:
      - "8073:8073"
    volumes:
      - "./settings.json:/var/lib/openwebrx/settings.json:ro"
