version: '3'

services:
  openwebrx:
    image: jketterl/openwebrx:stable
    devices:
      - "/dev/bus/usb"
    ports:
      - "8073:8073"
    volumes:
      - ".:/etc/openwebrx"  # Only need config file, but let's just map everything
